version: '3.8'
services:
    redis:
        image: redis
        ports:
            - 6379:6379
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.2
        ports:
            - 9200:9200
        environment:
            - discovery.type=single-node
            - action.auto_create_index=false
            - cluster.routing.allocation.disk.threshold_enabled=false
        volumes:
            - esdata:/usr/share/elasticsearch/data
    kibana:
        image: docker.elastic.co/kibana/kibana-oss:7.6.2
        depends_on:
            - elasticsearch
        ports:
            - 5601:5601
    worker:
        build: .
        volumes:
            - .:/app
        depends_on:
            - redis
            - elasticsearch

volumes:
  esdata: